language: python
python:
 - "2.7"
before_script:
 - sleep 15
services:
 - rabbitmq
install:
 - "pip install -r testing_requirements.txt && pip install -r requirements.txt"
 - "pip install --upgrade git+https://github.com/BeneDicere/metahosting-common"
script:
 - find . -name "*.py" -exec pep8 {} \;
 - nosetests --with-coverage --cover-package=queue_manager,status_updater
 - radon mi queue_manager status_updater
 - radon cc queue_manager status_updater
