cadvisor:
  image: google/cadvisor:latest
  volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
status:
  image: benedicere/metahosting-worker-status
  external_links:
    - metahostinghtml_messaging_1:messaging
  links:
    - cadvisor
  volumes:
    - /sys:/sys:ro
